name: Pipeline CI - DevPay


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
jobs:
  integracao-continua:
    runs-on: ubuntu-latest # servidor github

    steps:
    # baixa o código do repositório
    - name: Checkout do código
      uses: actions/checkout@v4

    # instalando o Node
    - name: Setup do Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # dependências
    - name: Instalação de dependências
      run: npm ci

   # verifica se o código está formatado
    - name: Verificação de Qualidade (Lint)
      run: npm run lint

    # compilador
    - name: Build da aplicação
      run: npm run build

    #  testes unitários
    - name: Testes Automatizados
      run: npm run test